### ISSUE TITLE
Where to get 'apollo_carla_bridge/docker'

### ISSUE THREAD

**Issue by 2019211753** [yizhiweimengxiangfendoudefeifei/apollo_carla_bridge#1]
May I ask where you cloned the apollo_carla_bridge/docker for running the 'Run apollo_carla_bridge' step? Did you clone it directly from here? https://github.com/guardstrikelab/carla_apollo_bridge

Actually, I found that the carla docker provided in https://github.com/guardstrikelab/carla_apollo_bridge cannot start and keeps restarting. Could you please provide some explanation or solutions for it? Thank you!

**Comment by 2019211753** [comment]
besides, after i  successfully built and run, my carla performs slowly. And my Dreamview don't get any change,
![image](https://user-images.githubusercontent.com/65377379/234600351-6ab8e339-6ea2-4e94-96ee-f5dbd851de6a.png)

My system is Ubuntu20.04. Using X11&Xmanager mapped to my local Windows11.

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
please run as follows:
cd apollo_carla_bridge/docker
./build_docker.sh
./run_docker.sh
docker exec -ti carla_cyber_0.9.13 bash
you can build docker. Carla performs slowly? I don't know why, maybe you can look at your GPU performance.
