### ISSUE TITLE
can i run apollo and carla in different machine?

### ISSUE THREAD

**Issue by 2019211753** [yizhiweimengxiangfendoudefeifei/apollo_carla_bridge#2]
how can i do it? I change the host from 172.17.0.2 to my windows machine ip in the /apollo/cyber/carla_bridge/config/settings.yml in the carla_cyber_0.9.13 container，but it dosen't work.

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
maybe, but i didn't try it.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月15日 11:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [yizhiweimengxiangfendoudefeifei/apollo_carla_bridge] can i run apollo and carla in different machine? (Issue #2) |

Closed #2 as completed.

**Comment by 2019211753** [comment]
I have tried it. By modifying the 'host' parameter in the 'settings.yaml' file located at '/apollo/cyber/carla_bridge/carla_cyber_bridge/config' within the 'apollo_cyber_0.9.13' container.

**Comment by 2019211753** [comment]
> maybe, but i didn't try it.
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年07月15日 11:18 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | Re: [yizhiweimengxiangfendoudefeifei/apollo_carla_bridge] can i run apollo and carla in different machine? (Issue #2) | Closed #2 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I have tried it. By modifying the 'host' parameter in the 'settings.yaml' file located at '/apollo/cyber/carla_bridge/carla_cyber_bridge/config' within the 'apollo_cyber_0.9.13' container.
